### ISSUE TITLE
problems with dynamic sizing

### ISSUE THREAD

**Issue by SoJeongmin** [tokkozhin/react-native-neomorph-shadows#21]
Hi.

I appreciate your contribution.  Thanks to your lib, I can make neomorph shadows much more easily.
But I have a problem with this lib in a certain situation.

When I set shadow size dynamically(I set shadow height as value from shadow's child comps height, using 'onLayout' props), the shadow render wrongly. But after changing view to other screen or other comp, then it render correctly(first render wrongly -> change view to other comp -> render correctly).

I hope you to check this issue.

Thanks!!

**Comment by tokkozhin** [comment]
Hey, thanks for your interest. I tried to make this opportunity, but the problem is that it is more re-rendering of components and therefore it affects performance.
It can be applied to your individual needs, outside the library.

But I think it might be an optional additional prop of shadows components in future, like: 
`<Shadow useLayout >`

**Comment by SoJeongmin** [comment]
Thank you for comments!

I tried several tries but I can't find solution.

So I resolve this problem by changing props(Actually, I don't use) after setting size of a shadow.
Then the shadow render properly.

I'm so sad that this is all the thing that I can do.

Hope this issue would be helpful to make your lib better.

Thank you again!!
